"""Add 20 new channels to Supabase. Run: python seed_more_channels.py"""
import os
from dotenv import load_dotenv
from supabase import create_client

load_dotenv()
supabase = create_client(os.getenv("SUPABASE_URL",""), os.getenv("SUPABASE_KEY",""))

NEW_CHANNELS = [
  {"id":"espn","short_name":"ESPN","full_name":"ESPN","tagline":"The Worldwide Leader in Sports","established":"Est. 1979","category":"Multi-Sport","country":"United States","hero_image":"https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1600&q=80","description":"ESPN is the world's largest sports network, broadcasting NFL, NBA, MLB, College Sports and more across America and globally via ESPN+.","sports":["NFL","NBA","MLB","MLS","College Sports"],"watch_url":"https://www.espn.com/watch","regions":[{"country":"United States","note":"Primary Network"},{"country":"Latin America","note":"ESPN Latam"},{"country":"Global","note":"ESPN+"}],"schedule":[{"time":"7:00 PM","category":"NBA","title":"LA Lakers vs Boston Celtics — LIVE","highlight":True},{"time":"10:00 PM","category":"NFL","title":"Monday Night Football: Chiefs vs Eagles"},{"time":"12:30 AM","category":"SportsCenter","title":"SportsCenter: Top 10 Plays"}],"affiliates":[{"id":"fox-sports-1","name":"Fox Sports 1","subtitle":"Rival Network"},{"id":"nbc-sports","name":"NBC Sports","subtitle":"Rights Partner"},{"id":"star-sports-1","name":"Star Sports","subtitle":"India Partner"}],"is_featured":True,"is_active":True,"viewers":2100000},

  {"id":"fox-sports-1","short_name":"FS1","full_name":"Fox Sports 1","tagline":"America's Sports Network","established":"Est. 2013","category":"Multi-Sport","country":"United States","hero_image":"https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=1600&q=80","description":"Fox Sports 1 is one of America's premier sports networks, covering UFC, NASCAR, NFL, MLB, College Football and World Cup Soccer.","sports":["UFC","NASCAR","NFL","MLB","Soccer"],"watch_url":"https://www.foxsports.com","regions":[{"country":"United States","note":"Primary Network"},{"country":"Canada","note":"Sportsnet Syndication"}],"schedule":[{"time":"8:00 PM","category":"UFC","title":"UFC 300: Main Card — LIVE","highlight":True},{"time":"11:00 PM","category":"NASCAR","title":"Daytona 500 Highlights"},{"time":"1:00 AM","category":"MLB","title":"World Series Game 7 Replay"}],"affiliates":[{"id":"espn","name":"ESPN","subtitle":"Rival Network"},{"id":"nbc-sports","name":"NBC Sports","subtitle":"Rights Partner"}],"is_featured":True,"is_active":True,"viewers":1450000},

  {"id":"sky-sports-pl","short_name":"SSPL","full_name":"Sky Sports Premier League","tagline":"Home of the Premier League","established":"Est. 1991","category":"Football","country":"United Kingdom","hero_image":"https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=1600&q=80","description":"Sky Sports Premier League is the UK's dedicated Premier League channel, broadcasting every match week with exclusive access, analysis and behind-the-scenes content for 5 million subscribers.","sports":["Premier League","EFL Cup","Community Shield","FA Cup"],"watch_url":"https://www.skysports.com/watch","regions":[{"country":"United Kingdom","note":"Primary Subscription"},{"country":"Ireland","note":"Sky Ireland"},{"country":"Germany","note":"Sky Deutschland"}],"schedule":[{"time":"12:30 PM","category":"Premier League","title":"Liverpool vs Man City — LIVE","highlight":True},{"time":"3:00 PM","category":"Premier League","title":"Arsenal vs Chelsea"},{"time":"5:30 PM","category":"Premier League","title":"Tottenham vs Man United"}],"affiliates":[{"id":"bein-sports","name":"beIN Sports","subtitle":"MENA Rights"},{"id":"espn","name":"ESPN","subtitle":"US Rights"}],"is_featured":True,"is_active":True,"viewers":1800000},

  {"id":"tnt-sports","short_name":"TNT","full_name":"TNT Sports","tagline":"Where Sport Gets Real","established":"Est. 2023","category":"Multi-Sport","country":"United Kingdom","hero_image":"https://images.unsplash.com/photo-1526232761682-d26e03ac148e?auto=format&fit=crop&w=1600&q=80","description":"TNT Sports (formerly BT Sport) holds rights to UEFA Champions League, Europa League, UFC, MotoGP, and top-flight boxing in the UK and Ireland.","sports":["UEFA Champions League","UFC","MotoGP","Boxing","Premier League"],"watch_url":"https://www.tntsports.co.uk","regions":[{"country":"United Kingdom","note":"Primary Broadcast"},{"country":"Ireland","note":"Available via Sky/Virgin"}],"schedule":[{"time":"8:00 PM","category":"Champions League","title":"Real Madrid vs Manchester City — LIVE","highlight":True},{"time":"10:30 PM","category":"UFC","title":"UFC Fight Night: Main Event"},{"time":"12:00 AM","category":"MotoGP","title":"Italian GP Highlights"}],"affiliates":[{"id":"sky-sports-pl","name":"Sky Sports","subtitle":"Distribution Partner"},{"id":"bein-sports","name":"beIN Sports","subtitle":"MENA Partner"}],"is_featured":True,"is_active":True,"viewers":920000},

  {"id":"canal-plus-sport","short_name":"C+S","full_name":"Canal+ Sport","tagline":"Le Sport en Direct","established":"Est. 1984","category":"Football","country":"France","hero_image":"https://images.unsplash.com/photo-1459865264687-595d652de67e?auto=format&fit=crop&w=1600&q=80","description":"Canal+ Sport is France's leading premium sports broadcaster, home to Ligue 1, Top 14 Rugby, and international football with over 8 million subscribers.","sports":["Ligue 1","Top 14 Rugby","Serie A","Premier League","Formule 1"],"watch_url":"https://www.canalplus.com/sport","regions":[{"country":"France","note":"Primary Market"},{"country":"Africa","note":"Canal+ Afrique"},{"country":"Poland","note":"Canal+ Poland"}],"schedule":[{"time":"9:00 PM","category":"Ligue 1","title":"PSG vs Marseille — LE CLASSIQUE LIVE","highlight":True},{"time":"11:30 PM","category":"Top 14","title":"Stade Toulousain vs Racing 92"},{"time":"2:00 AM","category":"Serie A","title":"AC Milan vs Inter: Derby della Madonnina"}],"affiliates":[{"id":"bein-sports","name":"beIN Sports","subtitle":"Content Partner"},{"id":"sky-sports-pl","name":"Sky Sports","subtitle":"UK Partner"}],"is_featured":False,"is_active":True,"viewers":650000},

  {"id":"dazn-global","short_name":"DAZN","full_name":"DAZN","tagline":"Sport Has a New Home","established":"Est. 2016","category":"OTT Giant","country":"United Kingdom","hero_image":"https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&w=1600&q=80","description":"DAZN is the world's largest dedicated sports streaming service, available in 200+ countries with rights to Boxing, MMA, NFL, Serie A, Bundesliga and La Liga.","sports":["Boxing","MMA","NFL","Serie A","Bundesliga","La Liga"],"watch_url":"https://www.dazn.com","regions":[{"country":"Global","note":"200+ Countries"},{"country":"Japan","note":"Primary Market"},{"country":"Germany","note":"Bundesliga Rights"},{"country":"Italy","note":"Serie A Rights"}],"schedule":[{"time":"10:00 PM","category":"Boxing","title":"Canelo Alvarez vs Benavidez — World Title","highlight":True},{"time":"1:00 AM","category":"NFL","title":"Super Bowl LVIII Live"},{"time":"4:00 PM","category":"Bundesliga","title":"Bayern Munich vs Borussia Dortmund"}],"affiliates":[{"id":"espn","name":"ESPN","subtitle":"US Content Partner"},{"id":"sky-sports-pl","name":"Sky Sports","subtitle":"UK Partner"}],"is_featured":True,"is_active":True,"viewers":3200000},

  {"id":"tsn-canada","short_name":"TSN","full_name":"TSN — The Sports Network","tagline":"Canada's Sports Leader","established":"Est. 1984","category":"Multi-Sport","country":"Canada","hero_image":"https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=1600&q=80","description":"TSN is Canada's most-watched sports network, broadcasting NHL, CFL, NBA, soccer and major international events to over 15 million Canadian households.","sports":["NHL","CFL","NBA","Soccer","Tennis"],"watch_url":"https://www.tsn.ca","regions":[{"country":"Canada","note":"National Network"},{"country":"United States","note":"TSN Direct"}],"schedule":[{"time":"7:00 PM","category":"NHL","title":"Toronto Maple Leafs vs Montreal Canadiens — LIVE","highlight":True},{"time":"9:30 PM","category":"CFL","title":"Grey Cup: Winnipeg vs Toronto"},{"time":"11:00 PM","category":"NBA","title":"Raptors vs Celtics Highlights"}],"affiliates":[{"id":"espn","name":"ESPN","subtitle":"Content Partner"},{"id":"fox-sports-1","name":"Fox Sports 1","subtitle":"Rights Partner"}],"is_featured":False,"is_active":True,"viewers":580000},

  {"id":"sporttv-brazil","short_name":"STV","full_name":"SporTV","tagline":"O Esporte Não Para","established":"Est. 1991","category":"Multi-Sport","country":"Brazil","hero_image":"https://images.unsplash.com/photo-1575361204480-aadea25e6e68?auto=format&fit=crop&w=1600&q=80","description":"SporTV is Brazil's leading sports cable network operated by Globo, covering Serie A Brasileirao, Copa Libertadores, Olympics, F1 and international football.","sports":["Brasileirao","Copa Libertadores","Olympics","F1","Tennis"],"watch_url":"https://www.globoplay.globo.com/canais/sportv","regions":[{"country":"Brazil","note":"Primary Network"},{"country":"Portugal","note":"Globosat Portugal"}],"schedule":[{"time":"8:30 PM","category":"Brasileirao","title":"Flamengo vs Palmeiras — LIVE","highlight":True},{"time":"11:00 PM","category":"Copa Libertadores","title":"Boca Juniors vs River Plate Semifinal"},{"time":"2:00 PM","category":"F1","title":"Brazilian Grand Prix: Race LIVE"}],"affiliates":[{"id":"espn","name":"ESPN","subtitle":"Rights Partner"},{"id":"dazn-global","name":"DAZN","subtitle":"Streaming Partner"}],"is_featured":False,"is_active":True,"viewers":720000},

  {"id":"star-sports-2","short_name":"SS2","full_name":"Star Sports 2","tagline":"International Sport in English","established":"Est. 1993","category":"Multi-Sport","country":"India","hero_image":"https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&w=1600&q=80","description":"Star Sports 2 is India's premium English-language sports channel, delivering Cricket, Football, Hockey, Tennis and Formula 1 with expert commentary to 60 million households.","sports":["Cricket","Football","Hockey","Tennis","F1"],"watch_url":"https://www.hotstar.com/in/sports","regions":[{"country":"India","note":"Primary Broadcast"},{"country":"South Asia","note":"Regional Feed"}],"schedule":[{"time":"7:00 PM","category":"Test Cricket","title":"India vs England Day 3 — LIVE","highlight":True},{"time":"11:00 PM","category":"Wimbledon","title":"Men's Quarter Finals"},{"time":"2:30 AM","category":"Formula 1","title":"Monaco Grand Prix Qualifying"}],"affiliates":[{"id":"star-sports-1","name":"Star Sports 1","subtitle":"Sister Channel"},{"id":"jiocinema","name":"JioCinema","subtitle":"Digital Partner"}],"is_featured":False,"is_active":True,"viewers":410000},

  {"id":"sports18","short_name":"S18","full_name":"Sports18","tagline":"The New Age Sports Network","established":"Est. 2022","category":"Multi-Sport","country":"India","hero_image":"https://images.unsplash.com/photo-1626248801379-51a0748a5f96?auto=format&fit=crop&w=1600&q=80","description":"Sports18 is Viacom18's flagship sports network, holding India rights to the FIFA World Cup, NHL, and NBA, rapidly growing to challenge established Indian sports broadcasters.","sports":["FIFA World Cup","NFL","NHL","NBA","Wrestling"],"watch_url":"https://www.jiocinema.com/sports","regions":[{"country":"India","note":"Primary Network"},{"country":"South Asia","note":"Extended Distribution"}],"schedule":[{"time":"8:00 PM","category":"FIFA","title":"World Cup 2026 Qualifier: India vs Kuwait","highlight":True},{"time":"10:30 PM","category":"NBA","title":"Golden State Warriors vs Miami Heat"},{"time":"6:00 AM","category":"NHL","title":"Stanley Cup: Florida Panthers vs Oilers"}],"affiliates":[{"id":"jiocinema","name":"JioCinema","subtitle":"OTT Partner"},{"id":"star-sports-1","name":"Star Sports 1","subtitle":"Rival Network"}],"is_featured":False,"is_active":True,"viewers":290000},

  {"id":"dd-sports","short_name":"DDS","full_name":"DD Sports","tagline":"India's Free Sports for All","established":"Est. 1999","category":"Free-To-Air","country":"India","hero_image":"https://images.unsplash.com/photo-1523831076786-57a8c462f809?auto=format&fit=crop&w=1600&q=80","description":"DD Sports is India's national free-to-air sports channel run by Doordarshan, bringing cricket, kabaddi, athletics, wrestling and indigenous Indian sports free to over 170 million households.","sports":["Cricket","Kabaddi","Athletics","Wrestling","Hockey"],"watch_url":"https://ddfreedishtv.gov.in","regions":[{"country":"India","note":"National Free-to-Air"},{"country":"South Asia","note":"DTH Distribution"}],"schedule":[{"time":"10:00 AM","category":"Pro Kabaddi","title":"Dabang Delhi vs Bengal Warriors — LIVE","highlight":True},{"time":"4:00 PM","category":"Athletics","title":"Asian Athletics Championships"},{"time":"7:00 PM","category":"Hockey","title":"India vs Malaysia: Asian Champions Trophy"}],"affiliates":[{"id":"star-sports-1","name":"Star Sports 1","subtitle":"Content Partner"},{"id":"sony-sports","name":"Sony Sports","subtitle":"Co-Broadcast"}],"is_featured":False,"is_active":True,"viewers":380000},

  {"id":"sky-sport-ger","short_name":"SKYde","full_name":"Sky Sport Bundesliga","tagline":"Echte Emotionen. Echter Fussball.","established":"Est. 2009","category":"Football","country":"Germany","hero_image":"https://images.unsplash.com/photo-1459865264687-595d652de67e?auto=format&fit=crop&w=1600&q=80","description":"Sky Sport Bundesliga is Germany's premium football channel, broadcasting every Bundesliga and Bundesliga 2 match with exclusive access for 5 million German subscribers.","sports":["Bundesliga","Bundesliga 2","DFB Pokal","Champions League","Europa League"],"watch_url":"https://www.sky.de/sport","regions":[{"country":"Germany","note":"Primary Market"},{"country":"Austria","note":"Sky Austria"},{"country":"Switzerland","note":"Sky CH"}],"schedule":[{"time":"6:30 PM","category":"Bundesliga","title":"Bayern Munich vs Borussia Dortmund — Der Klassiker","highlight":True},{"time":"8:30 PM","category":"Bundesliga","title":"Bayer Leverkusen vs RB Leipzig"},{"time":"3:30 PM","category":"Bundesliga","title":"Saturday Super Saturday: 3 Simultaneous Matches"}],"affiliates":[{"id":"dazn-global","name":"DAZN","subtitle":"Streaming Partner"},{"id":"canal-plus-sport","name":"Canal+ Sport","subtitle":"France Partner"}],"is_featured":False,"is_active":True,"viewers":510000},

  {"id":"movistar-laliga","short_name":"M+LL","full_name":"Movistar+ LaLiga","tagline":"Vive LaLiga","established":"Est. 2015","category":"Football","country":"Spain","hero_image":"https://images.unsplash.com/photo-1626248801379-51a0748a5f96?auto=format&fit=crop&w=1600&q=80","description":"Movistar+ LaLiga is Spain's exclusive La Liga broadcaster, delivering every match from the top two Spanish football divisions with 4K capabilities to 4 million subscribers.","sports":["La Liga","La Liga 2","Copa del Rey","Supercopa","UEFA"],"watch_url":"https://ver.movistarplus.es/deportes","regions":[{"country":"Spain","note":"Exclusive Rights"},{"country":"Latin America","note":"Movistar Deportes"}],"schedule":[{"time":"9:00 PM","category":"La Liga","title":"Real Madrid vs Barcelona — El Clasico","highlight":True},{"time":"6:30 PM","category":"La Liga","title":"Atletico Madrid vs Sevilla"},{"time":"4:15 PM","category":"Copa del Rey","title":"Athletic Club vs Villarreal SF"}],"affiliates":[{"id":"bein-sports","name":"beIN Sports","subtitle":"MENA Rights"},{"id":"dazn-global","name":"DAZN","subtitle":"Italy/Germany"}],"is_featured":True,"is_active":True,"viewers":870000},

  {"id":"abu-dhabi-sports","short_name":"ADS","full_name":"Abu Dhabi Sports","tagline":"Your Sports World","established":"Est. 2008","category":"Multi-Sport","country":"United Arab Emirates","hero_image":"https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=1600&q=80","description":"Abu Dhabi Sports is the UAE's premier sports network with 4 channels covering Premier League, UFC, F1, WWE and cricket, reaching 22 Arab countries via Etisalat and du.","sports":["Premier League","UFC","F1","WWE","Cricket"],"watch_url":"https://adtvsport.ae","regions":[{"country":"UAE","note":"Primary Network"},{"country":"Arab World","note":"22 Countries"},{"country":"MENA","note":"Pan-Arab Feed"}],"schedule":[{"time":"10:00 PM","category":"Premier League","title":"Man City vs Arsenal — LIVE","highlight":True},{"time":"12:30 AM","category":"UFC","title":"UFC 301: Main Card"},{"time":"4:00 PM","category":"F1","title":"Abu Dhabi Grand Prix Race Day"}],"affiliates":[{"id":"bein-sports","name":"beIN Sports","subtitle":"Regional Partner"},{"id":"sky-sports-pl","name":"Sky Sports","subtitle":"Content Partner"}],"is_featured":False,"is_active":True,"viewers":430000},

  {"id":"osn-sports","short_name":"OSN","full_name":"OSN Sports","tagline":"All the Action, All the Time","established":"Est. 2016","category":"Multi-Sport","country":"Saudi Arabia","hero_image":"https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=1600&q=80","description":"OSN Sports is a leading MENA sports broadcaster with exclusive WWE, Tennis Grand Slams, and select Premier League coverage reaching households across 22 Arab countries.","sports":["WWE","Tennis","Premier League","Boxing","Basketball"],"watch_url":"https://subscribe.osn.com/sports","regions":[{"country":"Saudi Arabia","note":"Primary Market"},{"country":"Kuwait","note":"OSN Kuwait"},{"country":"MENA","note":"Pan-Arab"}],"schedule":[{"time":"1:00 AM","category":"WWE","title":"WrestleMania 40: Main Card LIVE","highlight":True},{"time":"7:00 PM","category":"Tennis","title":"US Open Men's Final"},{"time":"10:00 PM","category":"Boxing","title":"World Heavyweight Championship"}],"affiliates":[{"id":"bein-sports","name":"beIN Sports","subtitle":"Football Rights"},{"id":"abu-dhabi-sports","name":"Abu Dhabi Sports","subtitle":"UAE Partner"}],"is_featured":False,"is_active":True,"viewers":310000},

  {"id":"sportsnet-canada","short_name":"SN","full_name":"Sportsnet","tagline":"The Home of Hockey","established":"Est. 1998","category":"Multi-Sport","country":"Canada","hero_image":"https://images.unsplash.com/photo-1575361204480-aadea25e6e68?auto=format&fit=crop&w=1600&q=80","description":"Sportsnet is Canada's most comprehensive sports network owned by Rogers, holding exclusive NHL national rights and broadcasting MLB, NBA, and CFL to 12 million subscribers.","sports":["NHL","MLB","NBA","CFL","Soccer"],"watch_url":"https://www.sportsnet.ca","regions":[{"country":"Canada","note":"National Broadcast"},{"country":"United States","note":"Streaming Only"}],"schedule":[{"time":"7:30 PM","category":"NHL","title":"Edmonton Oilers vs Colorado Avalanche — LIVE","highlight":True},{"time":"10:00 PM","category":"MLB","title":"Toronto Blue Jays vs New York Yankees"},{"time":"1:00 PM","category":"Soccer","title":"Canadian Premier League: Pacific FC vs Forge"}],"affiliates":[{"id":"tsn-canada","name":"TSN","subtitle":"Rival Network"},{"id":"espn","name":"ESPN","subtitle":"US Content Partner"}],"is_featured":False,"is_active":True,"viewers":490000},

  {"id":"fox-sports-asia","short_name":"FSA","full_name":"Fox Sports Asia","tagline":"Sport Unites Asia","established":"Est. 1996","category":"Multi-Sport","country":"Singapore","hero_image":"https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1600&q=80","description":"Fox Sports Asia broadcasts across Southeast Asia covering Premier League, NBA, NFL, UFC and regional football leagues to 30 million households across 10 countries.","sports":["Premier League","NBA","NFL","UFC","Asian Football"],"watch_url":"https://www.foxsportsasia.com","regions":[{"country":"Singapore","note":"Headquarters"},{"country":"Malaysia","note":"Astro Fox Sports"},{"country":"Thailand","note":"True Visions"},{"country":"Philippines","note":"Cable Partner"}],"schedule":[{"time":"8:30 PM","category":"Premier League","title":"Chelsea vs Newcastle — LIVE","highlight":True},{"time":"11:00 PM","category":"NBA","title":"Western Conference Finals Game 5"},{"time":"2:00 AM","category":"UFC","title":"UFC Singapore: Asian Card"}],"affiliates":[{"id":"espn","name":"ESPN","subtitle":"Content Partner"},{"id":"fox-sports-1","name":"Fox Sports 1","subtitle":"Parent Network"}],"is_featured":False,"is_active":True,"viewers":620000},

  {"id":"sky-sport-italy","short_name":"SSI","full_name":"Sky Sport Italia","tagline":"Il Meglio dello Sport","established":"Est. 2003","category":"Football","country":"Italy","hero_image":"https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=1600&q=80","description":"Sky Sport Italia is Italy's premium sports broadcaster with Serie A, Serie B, Champions League, Formula 1 and tennis reaching 5 million Italian subscribers.","sports":["Serie A","Serie B","Champions League","F1","Tennis"],"watch_url":"https://sport.sky.it","regions":[{"country":"Italy","note":"Primary Market"},{"country":"Switzerland","note":"Italian speaking regions"}],"schedule":[{"time":"8:45 PM","category":"Serie A","title":"Juventus vs Inter Milan — Derby d'Italia","highlight":True},{"time":"3:00 PM","category":"Serie A","title":"Sunday Big Match: AC Milan vs Napoli"},{"time":"2:00 PM","category":"F1","title":"Italian Grand Prix: Race from Monza"}],"affiliates":[{"id":"dazn-global","name":"DAZN","subtitle":"Streaming Partner"},{"id":"canal-plus-sport","name":"Canal+ Sport","subtitle":"France Partner"}],"is_featured":False,"is_active":True,"viewers":560000},

  {"id":"one-sports-ph","short_name":"ONE","full_name":"One Sports Philippines","tagline":"One Channel for All Sports","established":"Est. 2014","category":"Multi-Sport","country":"Philippines","hero_image":"https://images.unsplash.com/photo-1523831076786-57a8c462f809?auto=format&fit=crop&w=1600&q=80","description":"One Sports is the Philippines' leading free sports channel, broadcasting PBA basketball, UAAP, boxing and international football to 20 million Filipino households on free TV.","sports":["PBA","UAAP","Boxing","Football","NBA"],"watch_url":"https://www.ptvmedia.gov.ph/one-sports","regions":[{"country":"Philippines","note":"Free-to-Air National"},{"country":"Global","note":"Filipino diaspora via streaming"}],"schedule":[{"time":"7:00 PM","category":"PBA","title":"San Miguel Beermen vs Ginebra Kings — Finals G5","highlight":True},{"time":"9:30 PM","category":"UAAP","title":"UAAP Season 86: Ateneo vs La Salle"},{"time":"11:00 PM","category":"Boxing","title":"WBC World Title: Pinoy Pride Night"}],"affiliates":[{"id":"fox-sports-asia","name":"Fox Sports Asia","subtitle":"Regional Partner"},{"id":"espn","name":"ESPN","subtitle":"Content Licensor"}],"is_featured":False,"is_active":True,"viewers":340000},

  {"id":"nbc-sports","short_name":"NBC","full_name":"NBC Sports","tagline":"More Starts Here","established":"Est. 1989","category":"Multi-Sport","country":"United States","hero_image":"https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&w=1600&q=80","description":"NBC Sports is one of America's top sports networks broadcasting the Olympics, NFL Sunday Night Football, Premier League, NASCAR, PGA Tour and NHL to 90 million US households.","sports":["NFL","Olympics","Premier League","NASCAR","PGA Tour","NHL"],"watch_url":"https://www.peacocktv.com/sports","regions":[{"country":"United States","note":"National Broadcast"},{"country":"Global","note":"Peacock Streaming"}],"schedule":[{"time":"8:20 PM","category":"NFL","title":"Sunday Night Football: Dallas Cowboys vs NY Giants","highlight":True},{"time":"4:00 PM","category":"Premier League","title":"NBC Sports Gold PL Match"},{"time":"3:00 PM","category":"NASCAR","title":"Talladega 500 Race LIVE"}],"affiliates":[{"id":"espn","name":"ESPN","subtitle":"Rival Network"},{"id":"sky-sports-pl","name":"Sky Sports PL","subtitle":"Premier League Partner"}],"is_featured":True,"is_active":True,"viewers":1750000},
]

print(f"Seeding {len(NEW_CHANNELS)} new channels...")
ok = 0
for ch in NEW_CHANNELS:
    try:
        supabase.table("channels").upsert(ch, on_conflict="id").execute()
        print(f"  OK  {ch['full_name']}")
        ok += 1
    except Exception as e:
        print(f"  ERR {ch['full_name']}: {e}")
print(f"\nDone! {ok}/{len(NEW_CHANNELS)} inserted.")
